# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170330_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmarketingsignup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
