BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBB


BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXX XXXXX

        XXXXXX
        XXXX XXXXXXXXXXXXXX
        
        
                
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                XXXXX
                BBB BBBB BB BBBBBBB
                BB BBBBBBBBBBBBB
                    
                XXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXX
                    XXXXX
                    XXXX
                        XXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXXXXX
                        XXXXXFFFFFFFFFFFFFFFXXXXX
                        
                    XXXXX
                    XXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX
                XXXXX
                BBBB
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXXXX XX XXXX XXXXX XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXX XX XXXXXXXXXX
                BBBBB
                BBBBBB
            XXXXXXXX
            

        XXXXXX
        XXXX XXXXXXXXXXXXXX

        XXXXXX
        BBB BBBB BB BBBB
        
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XX XXXXXXXXXX XX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
             BBBBBBBB