# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170328_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
