# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 22:11
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=catalog.models.path_and_rename),
        ),
    ]
