# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.TextField(default=b'description default text'),
        ),
    ]
