BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Sign In') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
    XXXX gettext(u'Sign In') XXXXX

      XXXXXXXXX

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

      
         XXX gettext(u'If you have not created an account yet, then please\n        <a href="%(signup_url)s">sign up</a> first.') SS SSS SSSS SSS SSSSSSS SS SSSSSSS SSSS SSSS SSSSSS
        SS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS SSSSSSXXXX


        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
            BBBBBBBBBB
            FFFFFF
            BB BBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
            BBBBB
            XX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Forgot Password?') XXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Sign In') XXXXXXXXX
            XXXX
              XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXXXXXXX XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
