BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBB gettext(u'Signup') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX

	XXXX XXXXXXXXXXXXXXX
		XXXX gettext(u'Sign Up') XXXXX

		XXX gettext(u'Already have an account? Then please <a href="%(login_url)s">sign in</a>.') SSSSSSS SSSS SS SSSSSSSS SSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSXXXX

		XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
  			BBBBBBBBBB
  			FFFFFF
  			BB BBBBBBBBBBBBBBBBBBBB
  			XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XX
  			BBBBB
  			XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Sign Up')  XXXXXXXXXXXXXXXX
		XXXXXXX
	XXXXXX
XXXXXX
BBBBBBBB
