BBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                  X XXXX XX XXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
              XXXXXX
          XXXX XXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXX X XXXXXXXXXXX
              XX XXXXXXXXXXXXXX X XXXXXXXXXXXXXX
          XXXXXX  
XXXXXX