BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBB
BBBBB BBBBB
     X 
BBBBBBBB
BBBBB BBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBB
        BBBBBB
    XXXXXX
    BBBBBBBBBB BBBBBBB BBBBBBBBB BBBBBBBB
BBBBBBBB