    XXXX XXXXX XXXXXX XXX
    XXXXXXX
    XXXXXXX X
      XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX

    X
    XX X
      XXXXXXXXXXXX
    X

    XXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXX XXXXXXXXXX XXXXXXXXXXXX
            BBB BBBBBB BB BBBB
            BBB BBBBBBB BB BBBBB
            BBB BBBBBBBBB BB BBBBBBB
            XXX BB BBBBBBBBBBBB BB BBBB XXXXXXXXXXXXXX BBBBBXXX XXXXXXBBB BBBBBBXXXXXXXXXXXXXXX
            XXX BB BBBBBBBBBBBB BB BBBBB XXXXXXXXXXXXXX BBBBBXXX XXXXXXBBB BBBBBBBXXXXXXXXXXXXXXXX
            XXX BB BBBBBBBBBBBB BB BBBBBBB XXXXXXXXXXXXXX BBBBBXXX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXXXXXXX
            XXX BB BBBBBBBBBBBB BB BBBBBBB XXXXXXXXXXXXXX BBBBBXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX
                BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX
                BBBB
                XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
                BBBBB
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXX
              XXXXX
            XXXXX
          XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXXXXX
    XXXXXX