XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXX
            XXX XXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBBBBBBBBB
                    XXXBB BBBBBBBBBBBBBBB BB BBBB XXXXXXXXXXXXXXBBBBBX
                        XX XXXXXXXXXXXXXXXXXX
                    XXXXX
                BBBBBB
            XXXXX
        XXXXXX
    XXXXXX
XXXXXX