BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBB
BBBBB BBBBB
    XXXX XX XXXXXXXX X 
BBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBB
        BBBBBB
    XXXXXX
    XXXXXX
    
BBBBBBBB