BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBB

BBBBB BBBBB
     X 
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                XXXX XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXX XX XXXXXXXXXXXX XXXX XXXXX XXXX XXXXX XXXXX XXX XXXXXXXXXX
                    XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXX XXXXXXXX XXXXX XXXX
                    XXXX XX XXXX XXXXXXXXX XXXXXXXXX XX XXXXX XXXXXXXXXX XXXXXX XXXXX
                    XXXXX XXXX XXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXX XXXX XXXXXXXX
                    XXX XXXXXXXXXX XXX XXXX XXX XXXXXX XXX XXXX XXXXXXXXXXXX XXXXX
                    XXXXXXX XXX XXX XXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXX
                XXXXXXXX XXXXX
                XXXXXXXX XXXX XXX XXXXXXX XXXXX XXXX XXXXX XXX XXXXX XXXXXXXXXXXX
                XXXXXXXX XXXXXX XXX XXXX XXX XXXXXXX XXXX XXXX XXXXXXX XXXXXXXX
                XX XXXXXX XX XXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX XX XXXX
                XX XXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX
                XXXXXXXX XXXXXXXXXXX XXXX XX XXXXXXX XX XX XXXXXXX XXXXXXXXXXXX
                XXXX
                XXXXXXXXXX X XXXXXX XXXXXXXXXXX
                XXXXXXX XXXXX XXX XXX XXXX XXXXXXXXXXXXX XXX XX XX XXXXXXXXX XXXXX
                XXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXX XXXXXXX XXX
                XXXXXX XXX XXXXXXXX XXXXX XXXXXXXXXXXXX
            XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXX
                XXX XX XXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB